spring:
  r2dbc:
    url: r2dbcs:mysql://192.168.3.66:3306/spring_boot_r2dbc?sslMode=DISABLED&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: rootFwtai

server:
  port: 80